on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: "ubuntu-latest"
    
    steps:
      - uses: actions/checkout@v3

      - name: "Install CMake and Ninja"
        uses: lukka/get-cmake@latest

      - name: "Setup vcpkg"
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "78b61582c9e093fda56a01ebb654be15a0033897"

      - name: "Configure project"
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_SAMPLE=OFF -G Ninja -DCMAKE_TOOLCHAIN_FILE='${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake'

      - name: "Build project"
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
